---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - host_auth_variables

  vars_files:
    - vm_vars.yml

  tasks:
    - block:
        - name: Login to oVirt
          ovirt_auth:
            url: "{{ engine_url }}"
            username: "{{ engine_user }}"
            password: "{{ engine_password }}"
            ca_file: "{{ engine_cafile }}"
          tags:
            - always

    - name : Disk creation
      ovirt_disks:
            auth: "{{ ovirt_auth }}"
            state: attached
            vm_name: "{{item}}"
            name: rhel7_disk
            format: raw
            interface: virtio
            size: 20GiB
            storage_domain: datadom
      with_items:
          - rhel73_01           

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

