---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
     engine_url: https://dhcp31-210.perf.lab.eng.bos.redhat.com/ovirt-engine/api
     engine_user: admin@internal
     engine_password: 100yard-
     engine_cafile: /etc/pki/ovirt-engine/ca.pem

  vars_files:
    - vm_vars.yml

  tasks:
    - block:
        - name: Login to oVirt
          ovirt_auth:
            url: "{{ engine_url }}"
            username: "{{ engine_user }}"
            password: "{{ engine_password }}"
            ca_file: "{{ engine_cafile }}"
          tags:
            - always

    - name : Disk creation
      ovirt_disks:
            auth: "{{ ovirt_auth }}"
            state: attached
            vm_name: "{{item.vmname}}"
            name: "{{item.diskname}}"
            format: raw
            interface: virtio
            size: "{{item.size}}"
            storage_domain: datadom
      with_items:
          - { vmname: 'rhel73_01', diskname: 'rhel73_01_Disk5', size: '140GiB' } 
          - { vmname: 'rhel73_01', diskname: 'rhel73_01_Disk6', size: '140GiB' } 

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

