---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - host_auth_variables

  vars_files:
    - vm_vars.yml

  tasks:
    - block:
        - name: Login to oVirt
          ovirt_auth:
            url: "{{ engine_url }}"
            username: "{{ engine_user }}"
            password: "{{ engine_password }}"
            ca_file: "{{ engine_cafile }}"
          tags:
            - always

        - name: Create new VM 
          ovirt_vms:
            auth: "{{ ovirt_auth }}"            
            state: present
            cluster: perf
            name: newvm
            memory: 2GiB
            cpu_cores: 2
            cpu_sockets: 2
            cpu_shares: 1024
            type: server
            operating_system: rhel_7x64
            disks:
              - name: rhel7_disk
                name: rhel7_disk
                bootable: True
                size: 20GiB
                state: attached
                interface: virtio
                format: raw
                storage_domain: bootimages
            nics:
              - name: nic1

    - name : Disk creation
      ovirt_disks:
            name: rhel7_disk
            format: raw
            bootable: true
            interface: virtio
            size: 20GiB
            state: attached
            storage_domain: bootimages
           


    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

