---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - host_auth_variables


#     rhev.admin.name: admin
#     rhev.admin.pass: 100yard-
#     server_rhev: https://dhcp31-210.perf.lab.eng.bos.redhat.com/ovirt-engine/api

  tasks:
    - block:
        - name: Login to oVirt
          ovirt_auth:
            url: "{{ engine_url }}"
            username: "{{ engine_user }}"
            password: "{{ engine_password }}"
            ca_file: "{{ engine_cafile }}"
          tags:
            - always

        - name: Get VM Basic Info
          ovirt_hosts_facts:
            auth: "{{ ovirt_auth }}"
            pattern: name=perf9*
            fetch_nested: true
            nested_attributes: name
            
        - name: Show VM facts
          debug: 
            msg: "{{ item.0 }} is a host on this system."
          with_together:
            - "{{ovirt_hosts | map(attribute='name') | list}}"
          loop_control:
            label: "{{ item.0 }}"

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

