---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
     engine_url: https://dhcp31-210.perf.lab.eng.bos.redhat.com/ovirt-engine/api
     engine_user: admin@internal
     engine_password: 100yard-
     engine_cafile: /etc/pki/ovirt-engine/ca.pem

  tasks:
    - block:
        - name: Login to oVirt
          ovirt_auth:
            url: "{{ engine_url }}"
            username: "{{ engine_user }}"
            password: "{{ engine_password }}"
            ca_file: "{{ engine_cafile }}"
          tags:
            - always

#        - name: Get Host Info
#          ovirt_vms_facts:
#            auth: "{{ ovirt_auth }}"
#            pattern: name=rhel73_01
#            fetch_nested: true
#            nested_attributes: name

#        - name: Stop VM (to prepare for migration)
#          ovirt_vms:
#            auth: "{{ ovirt_auth }}" 
#            name: rhel73_01
#            state: stopped

        - name: Migrate VM from perf90 to perf92
          ovirt_vms:
            auth: "{{ ovirt_auth }}"
            state: running
            name: rhel73_01
            host: perf92
            poll: 0
#          with_together:
#            - "{{ovirt_vms | map(attribute='name') | list}}"
#            - "{{ovirt_vms | map(attribute='cluster') | list}}"
#          loop_control:
#            label: "{{ item.0 }}"
#          register: migrate_vm

#        - name: Start VM (see migration result)
#          ovirt_vms:
#            auth: "{{ ovirt_auth }}"
#            name: rhel73_01
#            state: running
#          poll: 0

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

