---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - host_auth_variables

  tasks:
    - block:
        - name: Login to oVirt
          ovirt_auth:
            url: "{{ engine_url }}"
            username: "{{ engine_user }}"
            password: "{{ engine_password }}"
            ca_file: "{{ engine_cafile }}"
          tags:
            - always

        - name: Modify VM characteristics
          ovirt_vms:
            auth: "{{ ovirt_auth }}"
            name: "{{item.vmname}}"
            cpu_sockets: "{{item.numsock}}"
            cpu_cores: "{{item.numcores}}"
            memory: "{{item.mem}}"
            memory_guaranteed: "{{item.memguar}}"
            state: stopped
          with_items:
            - { vmname: 'rhel73_01', numsock: '8', numcores: '1', mem: '58720256', memguar: '58720256' }
            - { vmname: 'rhel73_02', numsock: '8', numcores: '1', mem: '58720256', memguar: '58720256' }
            - { vmname: 'rhel73_03', numsock: '8', numcores: '1', mem: '58720256', memguar: '58720256' }
            - { vmname: 'rhel73_04', numsock: '8', numcores: '1', mem: '58720256', memguar: '58720256' }

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

