---
- name: oVirt infra
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - host_auth_variables


  tasks:
    - block:
        - name: Login to oVirt
          ovirt_auth:
            url: "{{ engine_url }}"
            username: "{{ engine_user }}"
            password: "{{ engine_password }}"
            ca_file: "{{ engine_cafile }}"
          tags:
            - always

    - name : Disk removal
      ovirt_disks:
            auth: "{{ ovirt_auth }}"
            state: absent
            vm_name: "{{item.vmname}}"
            name: "{{item.diskname}}"
      with_items:
          - { vmname: 'R73_01', diskname: 'R73_01_ssd_4Mshard_Disk1' } 
          - { vmname: 'R73_01', diskname: 'R73_01_ssd_4Mshard_Disk2' } 
          - { vmname: 'R73_02', diskname: 'R73_02_ssd_4Mshard_Disk1' } 
          - { vmname: 'R73_02', diskname: 'R73_02_ssd_4Mshard_Disk2' } 
          - { vmname: 'R73_03', diskname: 'R73_03_ssd_4Mshard_Disk1' } 
          - { vmname: 'R73_03', diskname: 'R73_03_ssd_4Mshard_Disk2' } 

    - name: Logout from oVirt
      ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
      tags:
        - always

